const images = {
    Applogo: require("../assest/Image/logo.png"),
    phone: require('../assest/Image/phone.png'),
    password: require('../assest/Image/password.png'),
    check: require('../assest/Image/check.png'),
    blank: require('../assest/Image/blank.png'),
    user: require('../assest/Image/user.png'),
    email: require('../assest/Image/email.png'),
    hidePassword: require('../assest/Image/hidePassword.png'),
    showPassword: require('../assest/Image/showPassword.png'),
    forgotIcon: require('../assest/Image/forgotIcon.png'),
    backIcon: require('../assest/Image/backIcon.png'),
    splash: require('../assest/Image/splash.png'),
    actHome: require('../assest/Image/actHome.png'),
    food: require('../assest/Image/food.png'),
    eatFood: require('../assest/Image/eatFood.png'),
    search: require('../assest/Image/search.png'),
    verify: require('../assest/Image/verify.png'),
    fevrate: require('../assest/Image/fevrate.png'),
    histry: require('../assest/Image/histry.png'),
    setting: require('../assest/Image/setting.png'),
    rectangle: require('../assest/Image/rectangle.png'),
    Group17: require('../assest/Image/Group17.png'),
    Group86: require('../assest/Image/Group86.png'),
    Group88: require('../assest/Image/Group88.png'),
    Group4: require('../assest/Image/Group4.png'),
    Group03: require('../assest/Image/Group03.png'),
    Rectangle59: require('../assest/Image/Rectangle59.png'),
    plus: require('../assest/Image/plus.png'),
    Group228: require('../assest/Image/Group228.png'),
    notification: require('../assest/Image/notification.png'),
    Shape: require('../assest/Image/Shape.png'),
    trash: require('../assest/Image/trash.png'),
    address: require('../assest/Image/address.png'),
    location: require('../assest/Image/location.png'),

};

export default images;
