const ApiUrl = {
    LOGIN: 'api/login',
    SIGNUP: "api/register",
    GENERATEOTP: "api/generateOtp?mobile=",
    VERIFYOTP: "api/verifyotp",
    NEWPASSWORD: "api/confirmpassword",
    FORGOTPASSWORD: "api/forgetPassword?mobile=",
    GETCATEGORY: "api/getAllCategory",
    CATEROGYLIST: "api/getProductByCategory?id=",
    addfavourite: "api/addfavourite?id=",
    getFavourite: "api/getFavourite",
    removeFavourite: "api/removeFavourite?id=",
    GETUSERPROFILE: "api/user?userId=",
    UPDATEPROFILE: "api/updateUser",
    GETDETAILS: "api/getProductById?id=",
    GETCARD: "api/getCarts",
    ADDCARD: "api/addCart",
    REMOVECARD: "api/removeCart?productId=",
    ADDQuantity: "api/updateCarts?productId=",
    GETADDRESS: "api/getAddresss",
    REMOVEADDRESS: "api/removeAddress?addressId=",
    ADDADDRESS: "api/addAddress",
    ORDERPLACE: "api/addPlaceOrder",
    ORDERHISTPRY: "api/getOrderHistory?status=",
    NOTIFICATION: "api/getAllNotification",
    CANCELORDER: "api/updateOrderStatus?id=",
    ODERDETAILS: "api/getOrderById?id="
}
export default ApiUrl